{
   "cis":"0",
   "source":"velobank-log-processor-onboarding ",
   "request":{
      "payload":{
         "RequestUUID":"test-e4bef337-fc01-42b8-9987-9353bebfcef9",
         "MID":"test-6674c393-cfc7-420b-874c-8d5dac3cab61",
         "ApplicantType":"NRA-CHN",
         "Partner":{
            "PartnerId":"31000112989176",
            "PartnerName":"WEBULL",
            "ApplicationIp":"223.237.237.6",
            "Channel":"Mobile",
            "VerificationResults":"Approved"
         },
         "Operation":"Create",
         "Accounts":[
            {
               "AccountType":"CHK_I_VELO",
               "AccountName":"Checking - US Checking",
               "CustomerToAccountRelationship":[
                  {
                     "CustomerAccountRelationshipCode":"Individual",
                     "CustomerAccountAssociationType":"Primary",
                     "NumberOfStatementCopies":0
                  }
               ]
            }
         ],
         "Customer":{
            "Names":[
               {
                  "Type":"English",
                  "FirstName":"Dach Turnpike",
                  "LastName":"Ssha"
               },
               {
                  "Type":"Chinese",
                  "FirstName":"?",
                  "LastName":"?"
               }
            ],
            "DateOfBirth":"1994-03-04",
            "Addresses":[
               {
                  "Type":"PrimaryAddress",
                  "IsForeignAddress":true,
                  "StreetAddress1":"hai dian qu zhong guan cun n an ",
                  "StreetAddress2":"3hao yan jiu sheng yuan ji ji shu y",
                  "StreetAddress3":"an jiu suo bei jing jing shi",
                  "City":"beijin",
                  "State":"bejin",
                  "Zip":"234",
                  "CountryCode":"CHN",
                  "Country":"China"
               },
               {
                  "Type":"MailingAddress",
                  "IsForeignAddress":false,
                  "StreetAddress1":"KYC-BBAE",
                  "StreetAddress2":"",
                  "City":"NEW YORK",
                  "State":"NY",
                  "Zip":"10005",
                  "CountryCode":"USA",
                  "Country":"United States of America"
               },
               {
                  "Type":"PrimaryChineseAddress",
                  "IsForeignAddress":true,
                  "StreetAddress1":"?????????",
                  "StreetAddress2":"?????????",
                  "StreetAddress3":"??? 100000",
                  "City":"",
                  "State":"",
                  "Zip":"",
                  "CountryCode":"CHN",
                  "Country":"??"
               },
               {
                  "Type":"MailingChineseAddress",
                  "IsForeignAddress":true,
                  "StreetAddress1":"?????????",
                  "StreetAddress2":"?????????",
                  "StreetAddress3":"??? 100000",
                  "City":"",
                  "State":"",
                  "Zip":"",
                  "CountryCode":"CHN",
                  "Country":"??"
               }
            ],
            "ContactInformation":[
               {
                  "Type":"Primary",
                  "Number":"17801219221",
                  "CountryCode":"+86",
                  "PhoneNumber":"+8617801219221"
               }
            ],
            "TaxIdType":"NoNumber",
            "CitizenshipCode":"CHN",
            "W8CertificateType":"W8BenNoCert",
            "PrimaryLanguage":"English",
            "EmailAddress":"33q222q123451236o1mkm@gmail.com",
            "CampaignId":"B",
            "Gender":"Male",
            "EmploymentOrSchool":"Employed",
            "EmploymentDate":"2019-12-12",
            "MaritalStatus":"Widowed",
            "MothersMaidenName":"",
            "Occupation":"UnemployedOrRetiredOrHomemaker",
            "TenPercentShareHolder":"No",
            "CountryOfDualCitizenship":"USA",
            "Position":"VP",
            "Employer":"",
            "YearEmployed":"6",
            "AnnualIncome":"UnderFiftyThousand",
            "TotalNetWorth":"0-50000 USD",
            "PrimaryBanking":"Hgbb",
            "W8CertificateDate":"2018-12-06T17:51:58+08:00",
            "EsignIsAccepted":"Yes",
            "EsignDateAccepted":"2018-12-07",
            "EsignTimeAccepted":"17:51:58+08:00",
            "TermsIsAccepted":"Yes",
            "TermsDateAccepted":"2018-12-07",
            "TermsTimeAccepted":"17:51:58+08:00",
            "IAccepted":"Yes",
            "IAcceptedDate":"2018-12-07",
            "IAcceptedTime":"17:51:58+08:00",
            "IsPoliticallyExposedPerson":"No",
            "EStatementAccepted":"Yes",
            "EStatementAcceptedDate":"2018-12-07",
            "EStatementAcceptedTime":"17:51:58+08:00",
            "NonResidentAccountInformation":{
               "SourceOfWealth":"Investments",
               "PurposeOfAccount":"Other",
               "IncomingWiresLimit":"ZeroToThreeThousand",
               "OutgoingWiresLimit":"ZeroToThreeThousand",
               "VisaType":"None",
               "ForeignTaxNumber":"41808611942697300"
            }
         },
         "Documents":[
            {
               "DocumentName":"NationalId",
               "DocumentType":"JPG",
              "DocumentDate":"2018-06-29T17:45:01.000+0000",
               "DocumentSource":"Chinese Government",
               "CountryCode":"CHN",
               "DocumentFrontImage":"",
               "DocumentBackImage":""
            }
         ],
         "ApplicationId":"APP-M-16074",
         "SalesforceApplicationId":"a042a000002ystyAAA"
      },
      "attributes":{
         "clientCertificate":null,
         "listenerPath":"/api/process/*",
         "requestPath":"/api/process/partner/account/create",
         "queryString":"",
         "remoteAddress":"/127.0.0.1:52547",
         "method":"POST",
         "scheme":"http",
         "relativePath":"/api/process/partner/account/create",
         "localAddress":"/127.0.0.1:8091",
         "requestUri":"/api/process/partner/account/create",
         "uriParams":{

         },
         "queryParams":{

         },
         "headers":{
            "content-type":"application/json",
            "authorization":"",
            "user-agent":"PostmanRuntime/7.20.1",
            "accept":"*/*",
            "cache-control":"no-cache",
            "postman-token":"31837700-f6e7-4528-af08-04077398ee84",
            "host":"localhost:8091",
            "accept-encoding":"gzip, deflate",
            "content-length":"5673",
            "connection":"keep-alive"
         },
         "version":"HTTP/1.1"
      }
   },
   "response":{
      "payload":{
         "data":{
            "ApplicationId":"APP-M-16074",
            "ApplicationStatus":"Approved",
            "CaseNumber":"CAS-98192-X6N2H8",
            "OktaId":"00uoxfenqpCGZHvnv0h7",
            "EnCustomerNumber":"DkjE0RZCUSFSMEbfcRhwYQ==",
            "CustomerNumber":"00000082190",
            "EnAccountNumber":"jBeWvov8OI7uSkIx3YX4RQ==",
            "AccountNumber":2161897487,
            "RequestUUID":"test-e4bef337-fc01-42b8-9987-9353bebfcef9",
            "ErrorMessageList":[
               {
                  "ErrorMessageNumber":null,
                  "ErrorMessageText":null
               }
            ]
         },
         "result":{
            "success":true,
            "code":"200",
            "message":"Success"
         }
      },
      "attributes":{

      }
   }
}
